packages:
  - packages/**
  - examples/**
  - '!**/test/**'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - vue-demi

patchedDependencies:
  vue-template-compiler: patches/vue-template-compiler.patch
