name: copy examples
# 在 master 分支推送代码的时候执行该脚本
on:
    push:
        branches:
            - master
# 授予写权限
permissions:
    contents: write
# 定义任务
jobs:
    # 任务一 - 打包 element-plus 版本文档
    build-and-deploy:
        # 运行环境
        runs-on: ubuntu-latest
        steps:
            # 第一步: 定义名称并使用插件(检出仓库代码)
            - name: get code
              uses: actions/checkout@v2

            # 第二步: 安装 pnpm
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            # 第三步: 设置 node 版本
            - name: Set node version to 20.12.0
              uses: actions/setup-node@v2
              with:
                  node-version: 20.12.0
                  # cache: pnpm

            - run: pnpm install

            # # 设置 vue 版本, 防止示例打包失败
            # - name: build
            #   run: pnpm switch3
            # 对示例包进行打包
            - name: build-example-plus-vue3
              run: pnpm build:plus-v3

            #     # 要操作的文件
            # - name: copy *.html
            #   uses: JamesIves/github-pages-deploy-action@v4
            #   with:
            #       folder: ./example/static
            #       # 复制到指定文件夹(可省略)(.: 根目录, ~: 绝对路径)
            #       target-folder: .
            #       single-commit: true
            #       clean: true
            #       clean-exclude: |
            #           *.js
            #           *.css

            - name: copy example-plus-vue3-dist
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: ./packages/element-plus/docs/.vitepress/dist/
                  target-folder: ./docs-plus
                  clean: true
    # 任务二 - 打包 element-plus 版本文档
    build-example-vue2:
        # 运行环境
        runs-on: ubuntu-latest
        steps:
            # 第一步: 定义名称并使用插件(检出仓库代码)
            - name: get code
              uses: actions/checkout@v2

            # 第二步: 安装 pnpm
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            # 第三步: 设置 node 版本
            - name: Set node version to 20.12.0
              uses: actions/setup-node@v2
              with:
                  node-version: 20.12.0
                  # cache: pnpm

            - run: pnpm install

            # # 设置 vue 版本, 防止示例打包失败
            # - name: build
            #   run: pnpm switch3
            # 对示例包进行打包
            - name: build-example-el-vue2
              run: pnpm build:el-v2

            #     # 要操作的文件
            # - name: copy *.html
            #   uses: JamesIves/github-pages-deploy-action@v4
            #   with:
            #       folder: ./example/static
            #       # 复制到指定文件夹(可省略)(.: 根目录, ~: 绝对路径)
            #       target-folder: .
            #       single-commit: true
            #       clean: true
            #       clean-exclude: |
            #           *.js
            #           *.css

            - name: copy example-el-vue2-dist
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: ./examples/el-vue2/dist/
                  target-folder: ./example-el-vue2
                  clean: true

    # # 任务二
    # task2:
    #     # 运行环境
    #     runs-on: ubuntu-latest
    #     steps:
    #         # 第一步: 定义名称并使用插件(检出仓库代码)
    #         - name: Checkout 🛎️
    #           # 使用插件
    #           uses: actions/checkout@v4

    #         # 第二步: 打包 example
    #         - name: Install and Build
    #           run: |
    #               npm install
    #               npm run build

    #         # 第三步: 使用插件将文件复制到 github-pages 中
    #         - name: Deploy 🚀
    #           uses: JamesIves/github-pages-deploy-action@v4
    #           with:
    #               # 要操作的文件
    #               folder: example/static
    #               # 复制到指定文件夹(可省略)(.: 根目录, ~: 绝对路径)
    #               target-folder: .
    #               clean: true
    #               clean-exclude: |
    #                   *.html
